# Generated by Django 4.2 on 2023-04-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproduct',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
