# Generated by Django 4.2 on 2023-04-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_storeuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeuser',
            name='create_at',
        ),
    ]
